### ISSUE TITLE
Rework error handling to allow multiple errors to trickle down to developer

### ISSUE THREAD

**Issue by Scottapotamas** [electricui/electricui-embedded#150]
The current error handling behaviour means that an error earlier in the chain can be overwritten by successes later on (write failure codes wiped by ack success). Its hard to see if there were errors in more than one spot!

## Proposal

Implement a bit-masked method which shares the full byte for the various classes of errors. This is described by the following "spec".

### Message handling has the following stages

1. Parsing data
2. Finding the 'tracked' variable
3. Actions (writes or callbacks)
4. Responses (ack/query)

### Bitfield Allocations

Following an assessment of each stage and the potential failure modes, assign the bits as follows (LSB ordered):

| Bit(s) 	|    Allocation    	|
|--------	|:----------------:	|
| 0, 1   	|   Parser Errors  	|
| 2      	|   Found tracked  	|
| 3, 4   	|   Action Errors  	|
| 5, 6   	|  Response Errors 	|
| 7      	| Reserved/Unalloc 	|

## Tasks

- [x] Rework error enum groups
- [x] Shift all check responsibilities inside each 'stage' function
- [x] Create macros to make error insertion readable
- [x] Use errors, and modify the way the status byte is passed around/mutated.
- [x] Modify tests to cope with this rework
- [x] Write macros/examples for devs to get this information out on their side
